# Generated by Django 4.1.2 on 2022-10-24 07:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_alter_myuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='ID',
        ),
        migrations.AddField(
            model_name='myuser',
            name='id',
            field=models.AutoField(default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
