# Generated by Django 4.1.2 on 2022-10-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_remove_myuser_id_myuser_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='userid',
        ),
        migrations.AddField(
            model_name='myuser',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
