# Generated by Django 4.1.2 on 2022-10-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_remove_myuser_userid_myuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
