# Generated by Django 4.1.2 on 2022-10-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_myuser_delete_useraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=True),
        ),
    ]
